site_name: juku3000
site_description: Kooliarvuti JUKU igavene digitaalne elu
site_url: https://j3k.infoaed.ee/
repo_name: infoaed/juku3000
repo_url: https://github.com/infoaed/juku3000
edit_uri: ""
site_author: juku3000
extra_css:
   - css/extra.css

theme:
    name: material
    logo: images/juku3000_small.svg
    favicon: images/favicon.svg
    language: et
    custom_dir: docs/overrides
    palette:
      - media: "(prefers-color-scheme)"
        primary: deep-purple
        toggle:
          icon: material/brightness-auto    
          name: "Automaatne heledus"
      - scheme: 'default'
        primary: deep-purple
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Tekst tumedal tasutal"
      - scheme: 'slate'
        primary: deep-purple
        media: '(prefers-color-scheme: dark)'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Tekst heledal taustal'
    features:
        - navigation.sections
        - header.autohide
        - content.code.copy
        - content.footnote.tooltips        

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - pymdownx.magiclink
    - toc:
        permalink: true

plugins:
  - social:

nav:
    - Tere, Juhan!: index.md
    - JUKU eluts√ºkkel: ajajoon.md
    - EKDOSi kasutamine: juku-k√§sud.md
    - MAME k√§ivitamine: mame-k√§ivitamine.md
    - Videote salvestamine: videod.md
    - Ketaste lugemine: kettad.md
    - Tarkvara kataloog: tarkvara-kataloog.md
    - M√§ngude ketas 2024: m√§ngude-ketas-2024.md
    - Porditud m√§ngud 2025: porditud-m√§ngud-2025.md
    - 'üëæ Proovi JUKUt veebis! üëæ': 'https://infoaed.ee/juku'
