site_name: juku3000
site_description: Kooliarvuti JUKU igavene digitaalne elu
site_url: https://juku3000.infoaed.ee/
repo_name: infoaed/juku3000
repo_url: https://github.com/infoaed/juku3000
edit_uri: ""
extra_css:
   - css/extra.css

theme:
    name: material
    logo: images/juku3000.svg
    favicon: images/favicon.svg
    language: et
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        primary: deep purple
        toggle:
          icon: 'material/lightbulb'
          name: "Tekst tumedal tasutal"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: deep purple
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Tekst heledal taustal'
    features:
        - navigation.sections
        - header.autohide
        - content.code.copy
        - content.footnote.tooltips        

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - toc:
        permalink: true

nav:
    - Tere, Juhan!: README.md
    - JUKU arvuti eluk√µver: ajajoon.md
    - Tarkvara kataloog: tarkvara-kataloog.md
    - EKDOSi kasutamine: juku-k√§sud.md
    - Ketaste lugemine: kettad.md
    - Videote salvestamine: videod.md
    - MAME k√§ivitamine: mame-k√§ivitamine.md
    - üëæ Proovi JUKUt veebis!: 'https://infoaed.ee/juku'
